### ISSUE TITLE
Recompensa

### ISSUE THREAD

**Issue by arthurfs0** [Turumbo/joseBot#1]
Será que não rola de você fazer mais uma parte no código pra confirmar as recompensas do passe? Porque quando sai da partida e tem que confirmar a recompensa, o script para de rodar

**Comment by Turumbo** [comment]
Opa, valeu pela participação. Eu posso sim, na verdade eu já uso o código modificado para isso mas ainda não atualizei aqui. Vou fazer isso agora!

**Comment by arthurfs0** [comment]
Tranquilo mano, muito obrigado! Gostei muito da programação, estava testando alguns macros, mas como a variação entre tempo de fila, tela de carregamento e tempo de partidas é grande, estava tendo alguns problemas... Valeu!

**Comment by Turumbo** [comment]
Que bom que gostou, espero que esteja sendo útil pra você tanto quanto para mim haha. Enfim, atualizei o código do repositório, você provavelmente vai saber atualizar seu código, mas de qualquer forma, as mudanças estão mostradas aqui:

https://github.com/Turumbo/joseBot/commit/97862935f7a40ed70ea7c58d5c5b45517bc4c5f2#diff-d6c0a4591426e7e579e973250976990bR227

Adicionei as coordenadas para o botão de aceitar recompensa da missão (tem que configurar elas de acordo com o seu monitor), a função para clicar nesse botão após os games e a chamada dessa função lá no final do loop. Se tiver qualquer problema só mandar aqui. Sucesso!
