### ISSUE TITLE
erro no identificador

### ISSUE THREAD

**Issue by arthurfs0** [Turumbo/joseBot#2]
E aí, beleza? Sou eu aqui de novo, hehe. Estou com um problema de erro na hora de aceitar a partida. Eu tenho uma noção de como funciona o código e tudo mais, mas não sei o motivo do erro, e queria saber se você poderia me ajudar.
O erro é esse:
Match found!
Traceback (most recent call last):
  File "Tokens.py", line 165, in <module>
    win32gui.SetForegroundWindow(leagueGame)
pywintypes.error: (1400, 'SetForegroundWindow', 'O identificador da janela é inválido.')

**Comment by Turumbo** [comment]
Salve amigo. Então, provavelmente você configurou errado o pixelDesktop. Tenha certeza de colocar ele em uma área **fora do client** e **dentro da tela do jogo** , de forma que, quando o jogo abrir, cubra esse pixel. Também vale ressaltar que seu papel de parede não pode mudar durante o uso do bot. Me conta ai como foi. o/

**Comment by arthurfs0** [comment]
Opa, e aí! Eu tinha colocado num pixel lateral, esse erro já tinha acontecido anteriormente, eu só não sabia o motivo. Alterei para uma localização na parte de cima do game e funcionou direitinho. Valeu!

**Comment by Turumbo** [comment]
Sucesso então, qualquer problema que tiver, só mandar aqui :D
