### ISSUE TITLE
Às vezes clica, às vezes não...

### ISSUE THREAD

**Issue by Lammina** [Turumbo/joseBot#3]
Oi José, tudo bom?

Estou com um problema e não estou conseguindo resolver: às vezes, quando coloco o python pra rodar, ele clica em encontrar partida, mas NÃO clica em Aceitar Partida... 
Remapeei novamente tudo de novo, e coloquei pra rodar e foi na primeira tentativa, porém no segundo game, mesmo problema... Vi que um rapaz teve um problema que eu também tenho às vezes do win32 não encontrar a janela, mudei umas 3 vezes de pixels... Mas aparentemente o problema que está dando quase que em 80% das vezes é o de não aceitar a partida.
In game, roda tudo certo, o problema está sendo em aceitar a partida. Pode me ajudar?

Agradeço desde já,

Lammina

**Comment by Turumbo** [comment]
Olá. Respondi na outra thread do amigo que está tendo o mesmo problema, vamos tentar resolver por lá. O problema do win32, além de poder ser causado pela configuração incorreta dos pixels, pode também ser causado pelo programa tentando manipular uma janela que ainda não existe, talvez pelo PC demorar um pouco para alternar entre elas. Seu PC sofre com isso? Ele demora muito para sair do cliente -> entrar no jogo -> retornar para o client? Valeu!

**Comment by Lammina** [comment]
Bom dia José!

Meu pc sofre sim com isso, meu notebook não é muito rápido.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Turumbo** [comment]
Hmmm então já sei o que pode ser o problema. O erro acontece depois que o jogo fecha ou antes dele abrir? No código tem alguns timers que "esperam" o jogo abrir e fechar por alguns segundos. Se, após esse tempo, seu jogo não estiver ainda aberto ou fechado, o programa pode bugar.

**Comment by Lammina** [comment]
José, eu alterei os "sleeps" e deu certo. Obrigado! O engraçado é: ele roda lisinho com o note de tampa aberta, se eu fecho a tampa (ele está configurado pra nunca suspender, hibernar, etc), ele acaba travando. Mas deu certo! Muito obrigado!

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Turumbo** [comment]
Ah, que bom que funcionou! Hmm isso é estranho mesmo, tenta ver no gerenciamento de energia se tem algo relacionado. No meu notebook eu uso ele em "Modo Desempenho", naqueles planos de energia, talvez isso possa ajudar. Sucesso!
