### ISSUE TITLE
Não clica em aceitar partida

### ISSUE THREAD

**Issue by rafadeath1** [Turumbo/joseBot#4]
ele apenas clica em encontrar partida, mas n clica em aceitar partida, vc poderia me ajudar?

**Comment by Lammina** [comment]
Estou com o mesmo problema aqui...

**Comment by Turumbo** [comment]
Olá, salve, vou tentar ajudar. Primeiro eu preciso de algumas informações. Quando ele clica em procurar partida, logo em seguida o mouse já se move para a posição definida do botão de aceitar partida? Ele exibe algum erro no console? Valeu!

**Comment by holaqurtal** [comment]
hi, sorry for speak english but im spanish and have the same problem, the program dont acept the game and in the consol i have this problem: pywintipes.error: 1400 'SetForeground window' the window identifier is not valid

**Comment by Turumbo** [comment]
Hi, it's okay. Hmm do you use static or dynamic background on your desktop? This might compromise the bot. Also, is this pywintypes error shown right after the program starts running and clicks to go in queue? ~Thanks
